project-knowledge:
  model: mistral.mistral-7b-instruct-v0:2
  seed: 42
  temperature: 0.0
  config:
    region: eu-west-3

action-plan:
  model: anthropic.claude-3-5-sonnet-20240620-v1:0
  seed: 42
  temperature: 0.0
  config:
    region: us-east-1

srf-analyze:
  model: us.deepseek.r1-v1:0
  seed: 42
  temperature: 0.0
  config:
    region: us-east-1

srf-tools:
  model: anthropic.claude-3-5-sonnet-20240620-v1:0
  seed: 42
  temperature: 0.0
  config:
    region: us-east-1

srs-analyze:
  model: gpt-4o-2024-08-06
  seed: 42
  temperature: 0.0

implement:
  model: gpt-4o-2024-08-06
  seed: 42
  temperature: 0.0

default:
  model: gpt-4o-mini-2024-07-18
  seed: 42
  temperature: 0.0
