project-knowledge:
  model: gpt-4o-mini-2024-07-18 # gpt-4.1-2025-04-14
  seed: 42
  temperature: 0.0

action-plan:
  model: gpt-4.1-2025-04-14
  seed: 42
  temperature: 0.0

srf-analyze:
  model: gpt-4o-mini-2024-07-18 # gpt-4.1-2025-04-14
  seed: 42
  temperature: 0.0

srf-tools:
  model: gpt-4o-mini-2024-07-18 # gpt-4.1-2025-04-14
  seed: 42
  temperature: 0.0

srs-analyze:
  model: gpt-4o-mini-2024-07-18 # gpt-4.1-2025-04-14
  seed: 42
  temperature: 0.0

implement:
  model: gpt-4.1-2025-04-14
  seed: 42
  temperature: 0.0

code-review:
  model: gpt-4.1-2025-04-14
  seed: 42
  temperature: 0.0

default:
  model: gpt-4o-mini-2024-07-18 # gpt-4.1-2025-04-14
  seed: 42
  temperature: 0.0
