project-knowledge:
  model: gemma3:12b-it-qat
  seed: 42
  temperature: 0.7

action-plan:
  model: gemma3:12b-it-qat
  seed: 42
  temperature: 0.7

srf-analyze:
  model: gemma3:12b-it-qat
  seed: 42
  temperature: 0.7

srf-tools:
  model: gemma3:12b-it-qat
  seed: 42
  temperature: 0.7

srs-analyze:
  model: gemma3:12b-it-qat
  seed: 42
  temperature: 0.7

implement:
  model: gemma3:12b-it-qat
  seed: 42
  temperature: 0.0

code-review:
  model: gemma3:12b-it-qat
  seed: 42
  temperature: 0.7

default:
  model: gemma3:12b-it-qat
  seed: 42
  temperature: 0.7
