project-knowledge:
  model: mistral.mistral-7b-instruct-v0:2
  seed: 42
  temperature: 0.0
  config:
    region: eu-west-3

action-plan:
  model: anthropic.claude-3-5-sonnet-20240620-v1:0
  seed: 42
  temperature: 0.0
  config:
    region: us-east-1

srf-analyze:
  model: us.deepseek.r1-v1:0
  seed: 42
  temperature: 0.0
  config:
    region: us-east-1

srf-tools:
  model: anthropic.claude-3-5-sonnet-20240620-v1:0
  seed: 42
  temperature: 0.0
  config:
    region: us-east-1

implement:
  model: anthropic.claude-3-5-sonnet-20240620-v1:0
  seed: 42
  temperature: 0.0
  config:
    region: us-east-1

default:
  model: mistral.mistral-7b-instruct-v0:2
  seed: 42
  temperature: 0.0
  config:
    region: eu-west-3
