remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: DeepNext
description: AI-powered software engineering assistant that converts issue descriptions into pull requests
show_downloads: true
github:
  repository_url: https://github.com/stxnext/deep-next
